### ISSUE TITLE
@ApplicationPath must have a "/" prefix?

### ISSUE THREAD

**Issue by mattjlewis** [oracle/helidon#1258]
My understanding of the JAX-RS specification is that leading and trailing '/' characters in paths are optional.
From the `@Path` annotation documentation: https://jax-rs.github.io/apidocs/2.0/:

> For the purposes of absolutizing a path against the base URI , a leading '/' in a path is ignored and base URIs are treated as if they ended in '/'.

My quick test indicates that this is true for `@Path` but that `@ApplicationPath` must have a leading '/'.

**Comment by tomas-langer** [comment]
Fixed in 1.x branch.

**Comment by mattjlewis** [comment]
Will this fix be included in the master branch (i.e. 2.0-SNAPSHOT)? I still get the same behaviour with 2.0-SNAPSHOT.

**Comment by tomas-langer** [comment]
It is now (with PR #1259 )
